name: Analysis

on:
  pull_request:
  push:
    branches: main
    paths: .
  workflow_dispatch:

jobs:
  analyze:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x
      - name: Install
        run: pip install -r dev.txt
      - name: Run Lint
        run: python -m start -l
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Checker: Auto Commit'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Unknownkz
          commit_user_email: unknownkz@outlook.co.id
          commit_author: Unknown <unknownkz@outlook.co.id>
